services:
  - type: web
    name: billplanner
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.11
    envVars:
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: OPENROUTER_API_KEY
        value: your-openrouter-api-key
