services:
  - type: web
    name: billplanner-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
